<?php

$field = array(
    'calcs_steelmax' => array(
        'id' => array(
            'name'          => 'id',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'user_id' => array(
            'name'          => 'user_id',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'region_id' => array(
            'name'          => 'region_id',
            'type'          => 'integer',
            'element'       => 'autocomplete',
            'is_required'   => 1,
        ),
        'city' => array(
            'name'          => 'city',
            'type'          => 'string',
            'element'       => 'combobox',
            'is_required'   => 1,
        ),
        'title' => array(
            'name'          => 'title',
            'type'          => 'string',
            'element'       => 'text',
            'is_required'   => 1,
        ),
        'phone' => array(
            'name'          => 'phone',
            'type'          => 'string',
            'element'       => 'text',
            'is_required'   => 1,
        ),
        'comments' => array(
            'name'          => 'comments',
            'type'          => 'string',
            'element'       => 'textarea',
        ),
        'date_created' => array(
            'name'          => 'date_created',
            'type'          => 'date',
            'element'       => 'date',
            'is_required'   => 1,
            'format'        => 'd.m.Y',
        ),
        'calc_type' => array(
            'name'          => 'calc_type',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
            'attr' => array(
                'first_hint'    => false,
            ),
        ),
        'custom_region_data' => array(
            'name'          => 'custom_region_data',
            'type'          => 'integer',
            'element'       => 'checkbox',
        ),
        'tray_id' => array(
            'name'          => 'tray_id',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'tray_is_valid' => array(
            'name'          => 'tray_is_valid',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'coef_n' => array(
            'name'          => 'coef_n',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_n1' => array(
            'name'          => 'coef_n1',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_n2' => array(
            'name'          => 'coef_n2',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_y' => array(
            'name'          => 'coef_y',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_q20' => array(
            'name'          => 'param_q20',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_np' => array(
            'name'          => 'param_np',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'coef_kf' => array(
            'name'          => 'coef_kf',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_kt' => array(
            'name'          => 'coef_kt',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_a' => array(
            'name'          => 'param_a',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_p' => array(
            'name'          => 'param_p',
            'type'          => 'float',
            'element'       => 'selectbox',
            'is_required'   => 1,
            'options' => array(
                '0.33' => 0.33,
                '0.5' => 0.5,
                '1' => 1,
                '2' => 2,
                '3' => 3,
                '5' => 5,
                '10' => 10,
                '20' => 20,
            ),
        ),
        'area_1' => array(
            'name'          => 'area_1',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_2' => array(
            'name'          => 'area_2',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_3' => array(
            'name'          => 'area_3',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_4' => array(
            'name'          => 'area_4',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_5' => array(
            'name'          => 'area_5',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_6' => array(
            'name'          => 'area_6',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_7' => array(
            'name'          => 'area_7',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_1m' => array(
            'name'          => 'area_1m',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'area_8m' => array(
            'name'          => 'area_8m',
            'type'          => 'float',
            'element'       => 'float',
            //'is_required'   => 1,
        ),
        'area' => array(
            'name'          => 'area',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format' => '%.3f',
        ),
        'area_m' => array(
            'name'          => 'area_m',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'large_roof_pitch' => array(
            'name'          => 'large_roof_pitch',
            'type'          => 'integer',
            'element'       => 'checkbox',
        ),
        'consumption_custom' => array(
            'name'          => 'consumption_custom',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'consumption_estimated' => array(
            'name'          => 'consumption_estimated',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_mr' => array(
            'name'          => 'coef_mr',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_zmid' => array(
            'name'          => 'param_zmid',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format' => '%.3f',
        ),
        'param_cmid' => array(
            'name'          => 'param_cmid',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format' => '%.3f',
        ),
        'tray_width' => array(
            'name'          => 'tray_width',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'tray_height' => array(
            'name'          => 'tray_height',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'tray_height_full' => array(
            'name'          => 'tray_height_full',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'tray_section_degree' => array(
            'name'          => 'tray_section_degree',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_h' => array(
            'name'          => 'tray_param_h',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_f' => array(
            'name'          => 'tray_param_f',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_w' => array(
            'name'          => 'tray_param_w',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_x' => array(
            'name'          => 'tray_param_x',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_rg' => array(
            'name'          => 'tray_param_rg',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_kn' => array(
            'name'          => 'tray_param_kn',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_ky' => array(
            'name'          => 'tray_param_ky',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_kc' => array(
            'name'          => 'tray_param_kc',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_ik' => array(
            'name'          => 'tray_param_ik',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format'        => '%.4f',
        ),
        'tray_param_lk' => array(
            'name'          => 'tray_param_lk',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_vcan' => array(
            'name'          => 'tray_param_vcan',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_tcon' => array(
            'name'          => 'param_tcon',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_tcan' => array(
            'name'          => 'tray_param_tcan',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_tr' => array(
            'name'          => 'tray_param_tr',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_consumption' => array(
            'name'          => 'tray_consumption',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'tray_param_dq' => array(
            'name'          => 'tray_param_dq',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_nb' => array(
            'name'          => 'param_nb',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'param_qb' => array(
            'name'          => 'param_qb',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_b' => array(
            'name'          => 'coef_b',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_qcal' => array(
            'name'          => 'param_qcal',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_vt' => array(
            'name'          => 'param_vt',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_dt' => array(
            'name'          => 'param_dt',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'consumption_total' => array(
            'name'          => 'consumption_total',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'phone' => array(
            'name'          => 'phone',
            'type'          => 'string',
            'element'       => 'text',
            'attr'  => array(
                'size'  => 20,
            ),
//            'is_required'   => in_array(USER_AREA, array('admin', 'engineer')) ? 0 : 1,
            'min'           => 10,
        ),
        'tray_material' => array(
            'name'          => 'tray_material',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'tray_load_class' => array(
            'name'          => 'tray_load_class',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'tray_type' => array(
            'name'          => 'tray_type',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'tray_series' => array(
            'name'          => 'tray_series',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'tray_title' => array(
            'name'          => 'tray_title',
            'type'          => 'string',
            'element'       => 'text',
            'is_required'   => 1,
        ),
        'tray_article' => array(
            'name'          => 'tray_article',
            'type'          => 'string',
            'element'       => 'text',
            'is_required'   => 1,
        ),
    ),
);

$config = array(
    'calcs_steelmax' => array(
        'print_bottom_text' => array(
            'name'          => 'print_bottom_text',
            'type'          => 'text',
            'element'       => 'textarea',
            'is_required'   => 1,
            //'country'       => 'ru',
            'title'         => 'Текст внизу страницы печати'
        ),
    ),
);

$label = array(
    'calcs_steelmax' => array(
        'ru' => array(
            'calcs_steelmax' => 'Расчет линейного водоотвода серии SteelMax',
            'id' => 'Номер расчета',
            'user_id' => 'Пользователь',
            'manager_id' => 'Менеджер',
            'engineer_id' => 'Инженер',
            'office_id' => 'Офис',
            'region_id' => 'Регион, в котором расположена площадь водосбора',
            'city' => 'Месторасположение площади водосбора', // Населенный пункт
            'title' => 'Название объекта',
            'comments' => 'Заменить текст примечания на странице печати', //'Комментарий',
            'date_created' => 'Дата создания',
            'calc_type' => 'Тип расчёта',
            'calc_type_1' => 'Подбор лотка по расходу сточных вод',
            'calc_type_2' => 'Подбор лотка на эксплуатируемой кровле',
            'calc_type_3' => 'Подбор лотка по площади водосбора',
            'custom_region_data' => 'Ввести параметры региона вручную',

            'phone' => 'Контактный телефон',
            'tray_material' => 'Материал лотка',
            'tray_load_class' => 'Класс нагрузки',
            'tray_type' => 'Тип лотка',
            'tray_type_1' => 'Тип 1 стандартный',
            'tray_type_2' => 'Тип 1 прикромочный',
            'tray_type_3' => 'Тип 2 стандартный',
            'tray_type_4' => 'Тип 2 прикромочный',
            'tray_type_5' => 'Тип 4',

            'step_1' => 'Шаг 1. Характеристика площади водосбора',
            'step_2' => 'Шаг 2. Характеристика линии лотков',
            'step_3' => 'Шаг 3. Выбор подходящего лотка',
            'step_4' => 'Шаг 4. Итог расчёта',
            'step_5' => 'Шаг 5',
            'step1' => 'Характеристика площади водосбора',
            'step2' => 'Характеристика линии лотков',
            'step3' => 'Результаты расчёта параметров лотка',
            'step4' => 'Итог расчёта',
            'step5' => '',
            'calc_all' => 'Результаты расчёта',
            'search' => 'Поиск расчёта',

            'tray_id' => 'Наименование лотка',
            'tray_title' => 'Наименование лотка',
            'tray_is_valid' => 'Лоток подходит',
            'tray_article' => 'Артикул лотка',
            'coef_n' => 'Гидравлический показатель степени, n',
            'coef_n1' => 'Гидравлический показатель степени, n1',
            'coef_n2' => 'Гидравлический показатель степени, n2',
            'coef_y' => 'Гидравлический показатель степени, γ',
            'param_q20' => 'Интенсивность дождя продолжительностью 20 мин при P=1 год, q20, л/(с*га)',
            'param_np' => 'Количество плеч линии лотков',
            'coef_kf' => 'Коэффициент, учитывающий неравномерность выпадения осадков по площади водосбора',
            'coef_kt' => 'Коэффициент, учитывающий снижение расчетного расхода при расчетной продолжительности дождя менее 10 мин',
            'param_a' => 'Параметр, характеризующий расчетный дождь, A',
            'param_p' => 'Период однократного превышения расчетной интенсивности, P, годы',
            'area_1' => 'Площадь кровли и асфальтобетонных покрытий, га',
            'area_2' => 'Площадь брусчатых мостовых и щебеночных покрытий, га',
            'area_3' => 'Площадь булыжных мостовых, га',
            'area_4' => 'Площадь щебеночных покрытий, не обработанных вяжущими, га',
            'area_5' => 'Площадь гравийных садово-парковых дорожек, га',
            'area_6' => 'Площадь спланированных грунтовых поверхностей, га',
            'area_7' => 'Площадь газонов, га',
            'area_1m' => 'Площадь кровли и асфальтобетонных покрытий, м2',
            'area_8m' => 'Площадь вертикальных стен, примыкающих к кровле, м2',
            'area' => 'Площадь водосбора, F, га',
            'area_m' => 'Площадь водосбора, F, м2',
            'large_roof_pitch' => 'Уклон кровли свыше 1,5%',
            'param_tcon' => 'Время поверхностной концентрации, tcon, мин',
            'consumption_custom' => 'Расход дождевого стока, л/с', // заданный пользователем
            'consumption_estimated' => 'Расчетный расход дождевого стока, Qr, л/с',
            'coef_mr' => 'Среднее количество дождей, mr',
            'param_zmid' => 'Средний коэффициент покрова, Zmid',
            'param_cmid' => 'Средний коэффициент стока, Ψmid',
            'tray_width' => 'Сечение лотка, мм', // Внутренняя ширина лотка, B, мм
            'tray_height' => 'Гидравлическая высота лотка, Hг, мм',
            'tray_height_full' => 'Полная высота лотка, H, мм',
            'tray_section_degree' => 'Степень заполнения лотка, h/H',
            'tray_param_h' => 'Наполнение лотка, h, м',
            'tray_param_f' => 'Угол φ',
            'tray_param_w' => 'Площадь живого сечения, ω, м2',
            'tray_param_x' => 'Смоченный периметр, χ, м',
            'tray_param_rg' => 'Гидравлический радиус, R, м',
            'tray_param_kn' => 'Степень шероховатости, nш',
            'tray_param_ky' => 'Показатель степени в коэффициенте Шези, y',
            'tray_param_kc' => 'Коэффициент Шези, C',
            'tray_param_ik' => 'Уклон линии лотков, i',
            'tray_param_lk' => 'Протяженность линии лотков, L, м',
            'tray_param_vcan' => 'Средняя скорость потока, v, м/с',
            'tray_param_tcan' => 'Время протекания воды по линии лотков, tcan, мин',
            'tray_param_tr' => 'Расчетная продолжительность дождя, tr, мин', // Время добегания воды до расчетно сечения, tr, мин
            'tray_consumption' => 'Фактический расход по лотку для данной степени наполнения, qл, л/с',
            'tray_param_dq' => 'Невязка расходов, |Δq|',
            'param_nb' => 'Количество точек сброса',
            'param_qb' => 'Расход на точку сброса, qв, л/с',
            'coef_b' => 'Коэффициент, учитывающий возникновение напорного режима, β',
            'param_qcal' => 'Расход для подбора диаметра, qcal, м3/с',
            'param_vt' => 'Средняя скорость потока в трубопроводе, vтр, м/с',
            'param_dt' => 'Рекомендуемый диаметр отводящего трубопровода, мм',
            'consumption_total' => 'Общий расход с линии лотков, л/с',
        ),
    ),
);

return array(
    "field" => $field,
    "config" => $config,
    "label" => $label,
);
