<?php

$field = array(
    'calcs_lositems' => array(
        'id' => array(
            'name'          => 'id',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'user_id' => array(
            'name'          => 'user_id',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'region_id' => array(
            'name'          => 'region_id',
            'type'          => 'integer',
            'element'       => 'autocomplete',
            'is_required'   => 1,
        ),
        'city' => array(
            'name'          => 'city',
            'type'          => 'string',
            'element'       => 'combobox',
            'is_required'   => 1,
        ),
        'title' => array(
            'name'          => 'title',
            'type'          => 'string',
            'element'       => 'text',
            'is_required'   => 1,
        ),
        'phone' => array(
            'name'          => 'phone',
            'type'          => 'string',
            'element'       => 'text',
            'is_required'   => 1,
        ),
        'comments' => array(
            'name'          => 'comments',
            'type'          => 'string',
            'element'       => 'textarea',
        ),
        'date_created' => array(
            'name'          => 'date_created',
            'type'          => 'date',
            'element'       => 'date',
            'is_required'   => 1,
            'format'        => 'd.m.Y',
        ),
        'calc_type' => array(
            'name'          => 'calc_type',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
            'attr' => array(
                'first_hint'    => false,
            ),
        ),
        'custom_region_data' => array(
            'name'          => 'custom_region_data',
            'type'          => 'integer',
            'element'       => 'checkbox',
        ),
        'item_id' => array(
            'name'          => 'item_id',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 0,
        ),
        'item_is_valid' => array(
            'name'          => 'item_is_valid',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'tank_id' => array(
            'name'          => 'tank_id',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 0,
        ),
        'tank_is_valid' => array(
            'name'          => 'tank_is_valid',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'provider_id' => array(
            'name'          => 'provider_id',
            'type'          => 'integer',
            'element'       => 'selectbox',
            'is_required'   => 1,
        ),
        'param_q20' => array(
            'name'          => 'param_q20',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_n' => array(
            'name'          => 'coef_n',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_n1' => array(
            'name'          => 'coef_n1',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_n2' => array(
            'name'          => 'coef_n2',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_y' => array(
            'name'          => 'coef_y',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_mr' => array(
            'name'          => 'coef_mr',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_hd' => array(
            'name'          => 'param_hd',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c' => array(
            'name'          => 'coef_c',
            'type'          => 'float',
            'element'       => 'selectbox',
            'is_required'   => 1,
            'options' => array(
                '0.85' => '0.85',
                '0.9' => '0.9',
                '1' => '1.0',
                '1.2' => '1.2',
            ),
        ),
        'coef_cv' => array(
            'name'          => 'coef_cv',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_cs' => array(
            'name'          => 'coef_cs',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_hcp' => array(
            'name'          => 'param_hcp',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_ha' => array(
            'name'          => 'param_ha',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_hp' => array(
            'name'          => 'param_hp',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_f' => array(
            'name'          => 'param_f',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_p' => array(
            'name'          => 'param_p',
            'type'          => 'float',
            'element'       => 'selectbox',
            'is_required'   => 1,
            'options' => array(
                '0.33' => 0.33,
                '0.5' => 0.5,
                '1' => 1,
                '2' => 2,
                '3' => 3,
                '5' => 5,
                '10' => 10,
                '20' => 20,
            ),
        ),
        'param_a' => array(
            'name'          => 'param_a',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'area_1' => array(
            'name'          => 'area_1',
            'type'          => 'float',
            'element'       => 'float',
            'format'        => '%.3f',
        ),
        'area_2' => array(
            'name'          => 'area_2',
            'type'          => 'float',
            'element'       => 'float',
            'format'        => '%.3f',
        ),
        'area_3' => array(
            'name'          => 'area_3',
            'type'          => 'float',
            'element'       => 'float',
            'format'        => '%.3f',
        ),
        'area_4' => array(
            'name'          => 'area_4',
            'type'          => 'float',
            'element'       => 'float',
            'format'        => '%.3f',
        ),
        'area_5' => array(
            'name'          => 'area_5',
            'type'          => 'float',
            'element'       => 'float',
            'format'        => '%.3f',
        ),
        'area_6' => array(
            'name'          => 'area_6',
            'type'          => 'float',
            'element'       => 'float',
            'format'        => '%.3f',
        ),
        'area_7' => array(
            'name'          => 'area_7',
            'type'          => 'float',
            'element'       => 'float',
            'format'        => '%.3f',
        ),
        'area' => array(
            'name'          => 'area',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format'        => '%.3f',
        ),
        'param_tcon' => array(
            'name'          => 'param_tcon',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_zmid' => array(
            'name'          => 'param_zmid',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format' => '%.3f',
        ),
        'param_cmid' => array(
            'name'          => 'param_cmid',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format'        => '%.3f',
        ),
        'param_lcan' => array(
            'name'          => 'param_lcan',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 0,
        ),
        'param_vcan' => array(
            'name'          => 'param_vcan',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 0,
        ),
        'param_lp' => array(
            'name'          => 'param_lp',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_vp' => array(
            'name'          => 'param_vp',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_tcan' => array(
            'name'          => 'param_tcan',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 0,
        ),
        'param_tp' => array(
            'name'          => 'param_tp',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_tr' => array(
            'name'          => 'param_tr',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_kt' => array(
            'name'          => 'coef_kt',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_kf' => array(
            'name'          => 'coef_kf',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c1' => array(
            'name'          => 'coef_c1',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c2' => array(
            'name'          => 'coef_c2',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c3' => array(
            'name'          => 'coef_c3',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c4' => array(
            'name'          => 'coef_c4',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c5' => array(
            'name'          => 'coef_c5',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c6' => array(
            'name'          => 'coef_c6',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_c7' => array(
            'name'          => 'coef_c7',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_z1' => array(
            'name'          => 'coef_z1',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_z2' => array(
            'name'          => 'coef_z2',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_z3' => array(
            'name'          => 'coef_z3',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_z4' => array(
            'name'          => 'coef_z4',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_z5' => array(
            'name'          => 'coef_z5',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_z6' => array(
            'name'          => 'coef_z6',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_z7' => array(
            'name'          => 'coef_z7',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_w' => array(
            'name'          => 'param_w',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_qr' => array(
            'name'          => 'param_qr',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_b' => array(
            'name'          => 'coef_b',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_qcal' => array(
            'name'          => 'param_qcal',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_plim' => array(
            'name'          => 'param_plim',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
            'format'        => '%.3f',
        ),
        'coef_k1' => array(
            'name'          => 'coef_k1',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'coef_k2' => array(
            'name'          => 'coef_k2',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_n' => array(
            'name'          => 'param_n',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_cz' => array(
            'name'          => 'param_cz',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_wt' => array(
            'name'          => 'param_wt',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_t1' => array(
            'name'          => 'param_t1',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_t2' => array(
            'name'          => 'param_t2',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_qlim' => array(
            'name'          => 'param_qlim',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_np' => array(
            'name'          => 'param_np',
            'type'          => 'integer',
            'element'       => 'integer',
            'is_required'   => 1,
        ),
        'param_qo' => array(
            'name'          => 'param_qo',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),
        'param_qon' => array(
            'name'          => 'param_qon',
            'type'          => 'float',
            'element'       => 'float',
            'is_required'   => 1,
        ),

        'tank_volume' => array(
            'name'          => 'tank_volume',
            'type'          => 'integer',
            'element'       => 'integer',
        ),
        'tank_diameter' => array(
            'name'          => 'tank_diameter',
            'type'          => 'integer',
            'element'       => 'integer',
        ),
        'tank_length' => array(
            'name'          => 'tank_length',
            'type'          => 'integer',
            'element'       => 'integer',
        ),

        'lositem_performance' => array(
            'name'          => 'lositem_performance',
            'type'          => 'float',
            'element'       => 'float',
        ),
        'lositem_diameter' => array(
            'name'          => 'lositem_diameter',
            'type'          => 'integer',
            'element'       => 'integer',
        ),
        'lositem_length' => array(
            'name'          => 'lositem_length',
            'type'          => 'integer',
            'element'       => 'integer',
        ),

    ),
);

$label = array(
    'calcs_lositems' => array(
        'ru' => array(
            'calcs_lositems' => 'Расчет очистных сооружений и емкостей TM Rainpark',
            'id' => 'Номер расчета',
            'user_id' => 'Пользователь',
            'manager_id' => 'Менеджер',
            'engineer_id' => 'Инженер',
            'office_id' => 'Офис',
            'region_id' => 'Регион, в котором расположена площадь водосбора',
            'city' => 'Месторасположение площади водосбора', // Населенный пункт
            'title' => 'Название объекта',
            'comments' => 'Заменить текст примечания на странице печати', //'Комментарий',
            'date_created' => 'Дата создания',
            'calc_type' => 'Тип расчета',
            //'calc_type_3' => 'Очистные сооружения с аккумулирующим резервуаром',
            //'calc_type_4' => 'Очистные сооружения с аккумулирующим резервуаром',
            //'calc_type_1' => 'Очистные сооружения проточного типа',
            //'calc_type_2' => 'Очистные сооружения проточного типа',
            'calc_type_3' => 'Расчет производительности ЛОС с аккумулирующим резервуаром для селитебных территорий',
            'calc_type_4' => 'Расчет производительности ЛОС с аккумулирующим резервуаром для предприятий 2-й группы',
            'calc_type_1' => 'Расчет производительности ЛОС проточного типа по расходу сточных вод',
            'calc_type_2' => 'Расчет производительности ЛОС проточного типа по площади водосбора',
            'calc_type_menu_3' => 'Расчет производительности ЛОС с аккумулирующим резервуаром для селитебных территорий',
            'calc_type_menu_4' => 'Расчет производительности ЛОС с аккумулирующим резервуаром для предприятий 2-й группы',
            'calc_type_menu_1' => 'Расчет производительности ЛОС проточного типа по расходу сточных вод',
            'calc_type_menu_2' => 'Расчет производительности ЛОС проточного типа по площади водосбора',
            'custom_region_data' => 'Ввести параметры региона вручную',

            'provider_id' => 'Поставщик емкости',
            'param_q20' => 'Интенсивность дождя продолжительностью 20 мин при P=1 год, q20, л/(с*га)',
            'coef_n' => 'Гидравлический показатель степени, n',
            'coef_n1' => 'Гидравлический показатель степени, n1',
            'coef_n2' => 'Гидравлический показатель степени, n2',
            'coef_y' => 'Гидравлический показатель степени, γ',
            'coef_mr' => 'Среднее количество дождей, mr',
            'param_hd' => 'Годовое количество жидких атмосферных осадков, Hд, мм',
            'coef_c' => 'Географический коэффициент C',
            'coef_cv' => 'Коэффициент вариации суточных осадков, Cv',
            'coef_cs' => 'Коэффициент асимметрии кривой обеспеченности, Cs',
            'param_hcp' => 'Средний максимум суточного слоя осадков, Hср',
//            'param_ha' => (defined('COUNTRY') && COUNTRY == 'by'
//                ? 'Максимальный слой осадков за дождь, ha, мм'
//                : 'Максимальный суточный слой осадков, ha'
//            ),
            'param_hp' => 'Максимальный суточный слой осадков, Hр, мм',
            'param_p' => 'Период однократного превышения расчетной интенсивности, P, годы',
            'param_f' => 'Нормированное отклонение, Ф',
            'param_tcon' => 'Время поверхностной концентрации, tcon, мин',
            'area_1' => 'Площадь кровли и асфальтобетонных покрытий, F1, га',
            'area_2' => 'Площадь брусчатых мостовых и щебеночных покрытий, F2, га',
            'area_3' => 'Площадь булыжных мостовых, F3, га',
            'area_4' => 'Площадь щебеночных покрытий, не обработанных вяжущими, F4, га',
            'area_5' => 'Площадь гравийных садово-парковых дорожек, F5, га',
            'area_6' => 'Площадь спланированных грунтовых поверхностей, F6, га',
            'area_7' => 'Площадь газонов, F7, га',
            'area' => 'Площадь водосбора, F, га',
            'param_lcan' => 'Протяженность линии лотков, Lcan, м',
            'param_vcan' => 'Расчетная скорость течения потока в линии лотков, vcan, м/с',
            'param_lp' => 'Протяженность сети дождевой канализации, Lp, м',
            'param_vp' => 'Расчетная скорость течения потока в сети дождевой канализации, vp, м/с',
            'param_tcan' => 'Время протекания воды по линии лотков, tcan, мин',
            'param_tp' => 'Время протекания воды по сети дождевой канализации, tp, мин',
            'param_tr' => 'Расчетная продолжительность дождя, tr, мин', // Время добегания воды до расчетного сечения
            'param_a' => 'Параметр, характеризующий расчетный дождь, A',
            'coef_kt' => 'Коэффициент, учитывающий снижение расчетного расхода при расчетной продолжительности дождя менее 10 мин',
            'coef_kf' => 'Коэффициент, учитывающий неравномерность выпадения осадков по площади водосбора',
            'coef_c1' => 'Коэффициент стока, Ψ1',
            'coef_c2' => 'Коэффициент стока, Ψ2',
            'coef_c3' => 'Коэффициент стока, Ψ3',
            'coef_c4' => 'Коэффициент стока, Ψ4',
            'coef_c5' => 'Коэффициент стока, Ψ5',
            'coef_c6' => 'Коэффициент стока, Ψ6',
            'coef_c7' => 'Коэффициент стока, Ψ7',
            'coef_z1' => 'Коэффициент покрова, Z1',
            'coef_z2' => 'Коэффициент покрова, Z2',
            'coef_z3' => 'Коэффициент покрова, Z3',
            'coef_z4' => 'Коэффициент покрова, Z4',
            'coef_z5' => 'Коэффициент покрова, Z5',
            'coef_z6' => 'Коэффициент покрова, Z6',
            'coef_z7' => 'Коэффициент покрова, Z7',
            'param_zmid' => 'Средний коэффициент покрова, Zmid',
            'param_cmid' => 'Средний коэффициент стока, Ψmid',
//            'param_w' => (defined('COUNTRY') && COUNTRY == 'by'
//                ? 'Объем стока от расчетного дождя, направляемый на очистку, Wa, м3'
//                : 'Объем стока от расчетного дождя, направляемый на очистку, Wос.д., м3' // Расчетный объем дождевых вод, отводимых на очистку, Wос, м3
//            ),
//            'param_qr' => (defined('COUNTRY') && COUNTRY == 'by'
//                ? 'Расчетный расход дождевого стока в подводящем коллекторе, qr, л/с'
//                : 'Расчетный расход дождевого стока в подводящем коллекторе перед разделительной камерой, Qr, л/с'
//            ),
            'coef_b' => 'Коэффициент, учитывающий возникновение напорного режима, β',
            'param_qcal' => 'Расход дождевого стока для гидравлического расчета сети дождевой канализации, Qcal, л/с',
            'param_plim' => 'Период однократного превышения интенсивности "предельного" дождя, Plim, годы', // , сток от которого направляется на очистку
//            'coef_k1' =>  (defined('COUNTRY') && COUNTRY == 'by'
//                ? 'Коэффициент разделения Kоч'
//                : 'Коэффициент K1'
//            ),
            'coef_k2' => 'Коэффициент K2',
            'param_n' => 'Количество параллельно установленных аккумулирующих резервуаров',
            'param_cz' => 'Коэффициент запаса',
            'param_wt' => 'Требуемый объем ёмкости, Wемк, м3',
            'param_t1' => 'Период переработки дождевого стока, отводимого на очистку, Точ, ч',
//            'param_t2' =>  (defined('COUNTRY') && COUNTRY == 'by'
//                ? 'Продолжительность технологических перерывов в течение периода переработки дождевого стока, Tт.п., ч'
//                : 'Продолжительность отстаивания стока в аккумулирующем резервуаре, Тотст, ч'
//            ),
//            'param_qlim' => (defined('COUNTRY') && COUNTRY == 'by'
//                ? 'Расчетная производительность очистных сооружений, Qоч, л/с'
//                : 'Расчетная производительность очистных сооружений, Qlim, л/с'
//            ),
            'param_qo' => 'Расчетная производительность очистных сооружений, Qоч, л/с',
            'param_np' => 'Количество параллельных линий очистных сооружений',
            'param_qon' => 'Требуемая производительность одной линии, л/с', // Расход на одну линию очистных сооружений

            'lositem_custom_title' => 'Нетиповые очистные сооружения индивидуального исполнения',
            'item_id' => 'Наименование очистного сооружения',
            'lositem_title' => 'Наименование',
            'lositem_performance' => 'Производительность, л/с',
            'lositem_diameter' => 'Диаметр, мм',
            'lositem_length' => 'Длина, мм',

            'tank_custom_title' => 'Нетиповая емкость индивидуального исполнения',
            'tank_id' => 'Наименование емкости',
            'tank_title' => 'Наименование емкости',
            'tank_volume' => 'Объём, м3',
            'tank_diameter' => 'Диаметр, мм',
            'tank_length' => 'Длина, мм',

            'step_1' => 'Шаг 1. Определение расчетной производительности очистных сооружений',
            'step_2' => 'Шаг 2. Итог расчета',
            'step1' => 'Характеристика площади водосбора по типам покрытия',
            'step2' => 'Определение расчетной производительности очистных сооружений',
            'step3' => 'Характеристика очистных сооружений',

            'calc_all' => 'Результаты расчёта',
            'search' => 'Поиск расчёта',
        ),
    ),
);

return array(
    "field" => $field,
    "label" => $label,
);
